//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seltzr.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seltzr.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .FilterWhere is functionally equivalent to .Filter(d =&gt; d.Where(expression)) but is more concise.
        /// </summary>
        internal static string SZ1001Description {
            get {
                return ResourceManager.GetString("SZ1001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {0}.FilterWhere instead of {0}.Filter and IQueryable.Where separately.
        /// </summary>
        internal static string SZ1001Message {
            get {
                return ResourceManager.GetString("SZ1001Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer FilterWhere.
        /// </summary>
        internal static string SZ1001Title {
            get {
                return ResourceManager.GetString("SZ1001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An overload for this method exists that accepts a lambda without an IApiContext parameter, use that instead..
        /// </summary>
        internal static string SZ1002Description {
            get {
                return ResourceManager.GetString("SZ1002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unused IApiContext parameter.
        /// </summary>
        internal static string SZ1002Message {
            get {
                return ResourceManager.GetString("SZ1002Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused Context Parameter.
        /// </summary>
        internal static string SZ1002Title {
            get {
                return ResourceManager.GetString("SZ1002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another builder method exists that simplifies this call.
        /// </summary>
        internal static string SZ1003Description {
            get {
                return ResourceManager.GetString("SZ1003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to {0} can be simplified.
        /// </summary>
        internal static string SZ1003Message {
            get {
                return ResourceManager.GetString("SZ1003Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call can be simplified.
        /// </summary>
        internal static string SZ1003Title {
            get {
                return ResourceManager.GetString("SZ1003Title", resourceCulture);
            }
        }
    }
}
